# Variable 'LOCATION' was defined in the Variables tab
# Variable 'ORACLE_HOST' was defined in the Variables tab
# Variable 'ORACLE_PASS' was defined in the Variables tab
# Variable 'ORACLE_PORT' was defined in the Variables tab
# Variable 'ORACLE_SID' was defined in the Variables tab
# Variable 'ORACLE_USER' was defined in the Variables tab
# Agent Queue 'Azure Pipelines' was used with unrecognized Agent Specification, vmImage property must be specified to determine image - https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software
# Agent Queue 'Azure Pipelines' was used with unrecognized Agent Specification, vmImage property must be specified to determine image - https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software
variables:
- name: BuildConfiguration
  value: 'Release'
- name: BuildParameters.RestoreBuildProjects
  value: '**/*.csproj'
- name: BuildParameters.TestProjects
  value: '**/*[Tt]ests/*.csproj'
trigger:
  branches:
    include:
    - refs/heads/main
name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job: Job_2
  displayName: Criar Infra Inicial
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
    fetchDepth: 1
  - task: AzureCLI@2
    displayName: Banco e Azure
    inputs:
      connectedServiceNameARM: 9668492c-9d55-4134-9d68-a078f19519bb
      scriptType: bash
      scriptPath: scripts/script-infra-app.sh
      scriptArguments: -ORACLE_HOST oracle.fiap.com.br -ORACLE_PORT 1521 -ORACLE_SID ORCL -ORACLE_USER rm558515 -ORACLE_PASS Fiap#2025 -LOCATION brazilsouth
- job: Job_1
  displayName: Build and Test
  dependsOn: Job_2
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
    fetchDepth: 1
  - task: UseDotNet@2
    displayName: 'Use .NET 8 SDK'
    inputs:
      packageType: 'sdk'
      version: '8.0.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - script: |
      echo "Verificando versão do .NET:"
      dotnet --version
      echo "Verificando SDKs instalados:"
      dotnet --list-sdks
    displayName: 'Verificar versão do .NET'
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: $(BuildParameters.RestoreBuildProjects)
      feedsToUse: 'select'
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: $(BuildParameters.RestoreBuildProjects)
      arguments: '--configuration $(BuildConfiguration) --no-restore'
  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: $(BuildParameters.TestProjects)
      arguments: '--configuration $(BuildConfiguration) --no-restore --logger "trx;LogFileName=test-results.trx" --results-directory "$(Agent.TempDirectory)/TestResults" --verbosity normal --diag "$(Agent.TempDirectory)/test-diag.log"'
      testRunTitle: 'Testes de CRUD'
  - script: |
      echo "Listando arquivos de teste gerados:"
      find $(Agent.TempDirectory)/TestResults -name "*.trx" -type f || echo "Nenhum arquivo .trx encontrado"
    displayName: 'Verificar arquivos de teste gerados'
    condition: always()
  - task: PublishTestResults@2
    displayName: Publish Test Results
    condition: succeededOrFailed()
    inputs:
      testRunner: VSTest
      testResultsFiles: '$(Agent.TempDirectory)/TestResults/**/*.trx'
      mergeTestResults: true
      testRunTitle: 'Testes de CRUD'
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: false
      projects: 'GenFit.API/GenFit.API.csproj'
      arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory) --no-build --no-restore'
      zipAfterPublish: true
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: app
      TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'
...